language: c

sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libfuse-dev libelf-dev python-dev gcc-arm-none-eabi python3-pip socat
    - pip install --user sh
    - pip3 install --user sh
    - pip install --user m3
    - pip3 install --user colorlog

before_script:
    - git clone https://github.com/gittup/tup.git
    - cd tup
    - ./build.sh
    - ./build/tup generate gen.sh
    - ./gen.sh
    - mkdir -p bin && cp tup bin/
    - PATH="$PWD/bin:$PATH"
    - cd ..

script:
    - ~/.local/bin/m3_ice_simulator &
    - ./ci_tests.py
