language: c

sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libfuse-dev python-dev gcc-arm-none-eabi
    - sudo pip install sh

## From http://stackoverflow.com/q/22111549 second answer
#install:
#    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; HACK=`which cc`; sudo rm $HACK; sudo ln -s `which gcc-4.8` $HACK; fi
#
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - gcc-4.8

before_script:
    - git clone https://github.com/ppannuto/tup.git
    - cd tup
    - git checkout generate_expand_groups 
    - ./build.sh
    - ./build/tup generate gen.sh
    - ./gen.sh
    - cd ..

script:
    - cd simulator
    - ../tup/tup generate build.sh --config configs/373-release
    - ./build.sh
