language: c

sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libfuse-dev python-dev gcc-arm-none-eabi python3-pip
    - pip install --user git+https://github.com/ppannuto/sh.git@fix_pushd
    - pip3 install --user git+https://github.com/ppannuto/sh.git@fix_pushd

before_script:
    - git clone https://github.com/gittup/tup.git
    - cd tup
    - ./build.sh
    - ./build/tup generate gen.sh
    - ./gen.sh
    - mkdir -p bin && cp tup bin/
    - PATH="$PWD/bin:$PATH"
    - cd ..

script:
    - ./ci_tests.py
